#!/bin/bash
# generates the xpm images, and the messages_list header and source files

set -eu

messages=( $(grep MESSAGE_ID_ message.h | sed 's/.*MESSAGE_ID_\(.*\),/\1/g') )
header=messages_list.h
source=messages_list.c

echo -e '/* generated by gen_message.sh - don t edit */\n' > ${header}
echo '#ifndef MESSAGES_LIST_H_A' >> ${header}
echo -e '#define MESSAGES_LIST_H_A\n' >> ${header}
echo -e '#include "utils.h"\n' >> ${header}

echo -e '/* generated by gen_message.sh - don t edit */\n' > ${source}
echo -e '#include "messages_list.h"' >> ${source}

for message in "${messages[@]}"
do
    message_lowercase=$(echo ${message} | tr "[A-Z]" "[a-z]")
    message_uppercase=$(echo ${message} | tr "_" " ")
    filename=res/messages/${message_lowercase}.xpm

    echo "creating ${filename}"

    convert -pointsize 16 -fill white \
            -draw "text 0,0 \"${message_uppercase}\" " \
            -gravity center -font res/04B_21__.ttf \
            res/blank.xpm ${filename}

    echo '#include "res/messages/'${message_lowercase}'.xpm"' >> ${source}
done
echo -e '#define MESSAGES_NB '${#messages[@]}'\n' >> ${header}
echo -e 'extern image *messages_list[MESSAGES_NB];\n' >> ${header}
echo '#endif' >> ${header}

echo -e '\nimage *messages_list[MESSAGES_NB] = {' >> ${source}

for message in "${messages[@]}"
do
    message_lowercase=$(echo ${message} | tr "[A-Z]" "[a-z]")
    echo -e "\t&${message_lowercase},"
done >> ${source}

echo '};' >> ${source}
