/* generated by gen_message.sh - don t edit */

#include "messages_list.h"
#include "res/messages/looser.xpm"
#include "res/messages/ready.xpm"
#include "res/messages/set.xpm"
#include "res/messages/go.xpm"
#include "res/messages/aim_dammit.xpm"
#include "res/messages/wake_up.xpm"
#include "res/messages/muahaha.xpm"
#include "res/messages/open_your_eyes.xpm"
#include "res/messages/are_you_blind.xpm"
#include "res/messages/too_bad.xpm"
#include "res/messages/are_you_drunk.xpm"
#include "res/messages/chicken.xpm"
#include "res/messages/alien_laughing.xpm"
#include "res/messages/not_that_bad.xpm"
#include "res/messages/well_done.xpm"
#include "res/messages/good.xpm"
#include "res/messages/born_to_kill.xpm"
#include "res/messages/lucky_i_m_not_an_alien.xpm"
#include "res/messages/killing_machine.xpm"
#include "res/messages/sniper.xpm"
#include "res/messages/unstoppable.xpm"
#include "res/messages/alien_slaughterer.xpm"
#include "res/messages/like_a_god.xpm"

image *messages_list[MESSAGES_NB] = {
	&looser_xpm,
	&ready_xpm,
	&set_xpm,
	&go_xpm,
	&aim_dammit_xpm,
	&wake_up_xpm,
	&muahaha_xpm,
	&open_your_eyes_xpm,
	&are_you_blind_xpm,
	&too_bad_xpm,
	&are_you_drunk_xpm,
	&chicken_xpm,
	&alien_laughing_xpm,
	&not_that_bad_xpm,
	&well_done_xpm,
	&good_xpm,
	&born_to_kill_xpm,
	&lucky_i_m_not_an_alien_xpm,
	&killing_machine_xpm,
	&sniper_xpm,
	&unstoppable_xpm,
	&alien_slaughterer_xpm,
	&like_a_god_xpm,
};
