/* generated by gen_message.sh - don t edit */

#include "messages_list.h"
#include "res/messages/looser.xpm"
#include "res/messages/ready.xpm"
#include "res/messages/set.xpm"
#include "res/messages/go.xpm"
#include "res/messages/aim_dammit.xpm"
#include "res/messages/wake_up.xpm"
#include "res/messages/muahaha.xpm"
#include "res/messages/open_your_eyes.xpm"
#include "res/messages/are_you_blind.xpm"
#include "res/messages/too_bad.xpm"
#include "res/messages/are_you_drunk.xpm"
#include "res/messages/chicken.xpm"
#include "res/messages/alien_laughing.xpm"
#include "res/messages/not_that_bad.xpm"
#include "res/messages/well_done.xpm"
#include "res/messages/good.xpm"
#include "res/messages/born_to_kill.xpm"
#include "res/messages/lucky_i_m_not_an_alien.xpm"
#include "res/messages/killing_machine.xpm"
#include "res/messages/sniper.xpm"
#include "res/messages/unstoppable.xpm"
#include "res/messages/alien_slaughterer.xpm"
#include "res/messages/like_a_god.xpm"

image *messages_list[MESSAGES_NB] = {
	&looser,
	&ready,
	&set,
	&go,
	&aim_dammit,
	&wake_up,
	&muahaha,
	&open_your_eyes,
	&are_you_blind,
	&too_bad,
	&are_you_drunk,
	&chicken,
	&alien_laughing,
	&not_that_bad,
	&well_done,
	&good,
	&born_to_kill,
	&lucky_i_m_not_an_alien,
	&killing_machine,
	&sniper,
	&unstoppable,
	&alien_slaughterer,
	&like_a_god,
};
